version: '3'
services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
volumes:
  mongodb-data:
  redis-data: