name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  NODE_VERSION: 12.22.1
  PROJECT_ID: movierater-1492834745733

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: yarn install

    - name: Build application
      run: yarn build

    - name: Install Docker Compose
      run: |
        sudo apt-get update && \
        sudo apt-get -y install docker-compose

    - name: Start services
      run: docker-compose up -d

    - name: Wait for services to start
      run: sleep 15

    - name: Run tests
      run: yarn test

    - name: Stop services
      run: docker-compose down

    - name: Build Docker image
      if: ${{ github.event.pull_request.merged }}
      run: |
        docker build -t asia-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/movierater/movierater .

    - name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      if: ${{ github.event.pull_request.merged }}
      with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - name: 'gcloud login'
      if: ${{ github.event.pull_request.merged }}
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list

    - name: Push Docker image to Artifact Registry
      if: ${{ github.event.pull_request.merged }}
      run: |
        docker push asia-east1-docker.pkg.dev/${{ env.PROJECT_ID }}/movierater/movierater